# Coding Along on Numpy #

### First is the installation ###

In [17]:
import numpy as np
# 1D array
a= np.array([2,4,3,5,6])
b= np.array([[2,3,5,5,4],
             [4,2,1,23,5]])
c= np.array([
    [
        [6,7,7],
        [5,4,5]
    ],
    [
        [0,8,3],
        [2,45,22]
    ],
    [
        [65,64,0],
        [44,21,17]
     ]
     ])

print(f"This is a 1D array:\n{a}\n")
print(f"This is a 2D array:\n{b}\n")
print(f"This is a 3D array:\n{c}")

This is a 1D array:
[2 4 3 5 6]

This is a 2D array:
[[ 2  3  5  5  4]
 [ 4  2  1 23  5]]

This is a 3D array:
[[[ 6  7  7]
  [ 5  4  5]]

 [[ 0  8  3]
  [ 2 45 22]]

 [[65 64  0]
  [44 21 17]]]


In [28]:
arr=np.array(((4,3,3),
             (7,8,0),
             (5,7,3)))

arr[0,1]=80
print(arr[0,1])
print(arr)

80
[[ 4 80  3]
 [ 7  8  0]
 [ 5  7  3]]


In [33]:
zeros =np.zeros((4,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
ones =np.ones(((2,3,4)))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [46]:
new_array= np.arange(0,2000,2)
print(f"The new array is {new_array}")
sum=new_array.sum()
# size=new_array.size()
mean= new_array.mean()
min=new_array.min()
print(f"The sum of the array is: {sum}")
# print(f"The size of the array is: {size}")
print(f"The mean of the array is: {mean}")
print(f"The min of the array is: {min}")


The new array is [   0    2    4    6    8   10   12   14   16   18   20   22   24   26
   28   30   32   34   36   38   40   42   44   46   48   50   52   54
   56   58   60   62   64   66   68   70   72   74   76   78   80   82
   84   86   88   90   92   94   96   98  100  102  104  106  108  110
  112  114  116  118  120  122  124  126  128  130  132  134  136  138
  140  142  144  146  148  150  152  154  156  158  160  162  164  166
  168  170  172  174  176  178  180  182  184  186  188  190  192  194
  196  198  200  202  204  206  208  210  212  214  216  218  220  222
  224  226  228  230  232  234  236  238  240  242  244  246  248  250
  252  254  256  258  260  262  264  266  268  270  272  274  276  278
  280  282  284  286  288  290  292  294  296  298  300  302  304  306
  308  310  312  314  316  318  320  322  324  326  328  330  332  334
  336  338  340  342  344  346  348  350  352  354  356  358  360  362
  364  366  368  370  372  374  376  378  380  382  384  386

In [49]:
space_by_line= np.linspace(0,3,10)
print(f"line space by 10: {space_by_line}")

logspace= np.logspace(2,10,90)
print(logspace)

line space by 10: [0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]
[1.00000000e+02 1.22995052e+02 1.51277828e+02 1.86064243e+02
 2.28849813e+02 2.81473946e+02 3.46199027e+02 4.25807673e+02
 5.23722369e+02 6.44152600e+02 7.92275825e+02 9.74460063e+02
 1.19853766e+03 1.47414202e+03 1.81312174e+03 2.23005003e+03
 2.74285120e+03 3.37357126e+03 4.14932572e+03 5.10346533e+03
 6.27700983e+03 7.72041151e+03 9.49572415e+03 1.16792709e+04
 1.43649253e+04 1.76681473e+04 2.17309470e+04 2.67279895e+04
 3.28741046e+04 4.04335220e+04 4.97312315e+04 6.11669540e+04
 7.52323269e+04 9.25320396e+04 1.13809830e+05 1.39980460e+05
 1.72169039e+05 2.11759399e+05 2.60453583e+05 3.20345020e+05
 3.94008524e+05 4.84610990e+05 5.96047539e+05 7.33108980e+05
 9.01687771e+05 1.10903134e+06 1.36405368e+06 1.67771853e+06
 2.06351078e+06 2.53801615e+06 3.12163429e+06 3.83945572e+06
 4.72234056e+06 5.80824522e+06 7.14385423e+06 8.78658723e+06
 1.08070675e+07

In [ ]:
arr= np.array([3,7,9,12,54,7,66,12])
fancyselect= np.array([0,2,5])